/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDNSJO5RLRwQAV5S8JNRqUcQ",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-27be9440",
            securityGroupIds: [
                "sg-0f6c346ced2d6a78f"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-bac4f5e1",
                    availabilityZone: "us-west-1c"
                },
                {
                    subnetId: "subnet-9d4da8fb",
                    availabilityZone: "us-west-1a"
                }
            ]
        }
    }
}).schema({
    "member": a.model({
        member_id: a.string().required(),
        first: a.string().required(),
        last: a.string().required(),
        prefix: a.string().required(),
        suffix: a.string().required(),
        email: a.string().required(),
        email2: a.string().required(),
        phone: a.string().required(),
        birthday: a.integer().required(),
        creation: a.integer().required(),
        update: a.integer().required(),
        active: a.string().required(),
        schedualable: a.string().required(),
        sub: a.string().required(),
    }).identifier([
        "member_id"
    ])
});
